<?php
define('_DB_HOST_','localhost');
define('_DEFAULT_TIMEZONE_OFFSET_','1');
define('_DB_NAME_','project_ediarosms');
define('_DB_PREFIX_','ed_');
define('_DB_USERNAME_','root');
define('_DB_PASS_','');
define('_ADMIN_EMAIL_','proff.tormuto@gmail.com');
define('_ADMIN_PASS_','omodaadaa');
?>